spring:
  threads:
    virtual:
      enabled: true

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/${DB_NAME:stormapi}
    username: ${DB_USER:stormapi}
    password: ${DB_PASSWORD:}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: false

  h2:
    console:
      enabled: false

logging:
  level:
    com.stormapi: INFO
    org.springframework.web: WARN
